version: "3.9"

services:
  redis:
    image: redis:7.2-alpine
    container_name: my-redis
    ports:
      - "6379:6379"           # mappa la porta locale 6379
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data: